# Generated by Django 5.2.6 on 2025-09-26 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('crop_name', models.CharField(max_length=100)),
                ('crop_stage', models.CharField(choices=[('seedling', 'Seedling'), ('vegetative', 'Vegetative'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('harvest', 'Harvest Ready')], max_length=20)),
                ('soil_moisture', models.FloatField(help_text='Soil moisture percentage')),
                ('soil_ec', models.FloatField(help_text='Electrical conductivity (mS/cm)')),
                ('soil_ph', models.FloatField(help_text='pH level')),
                ('vpd', models.FloatField(help_text='Vapor Pressure Deficit (kPa)')),
                ('light_intensity', models.FloatField(help_text='Light intensity (lux)')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
